from pathlib import Path


def replace_once(path: str, old: str, new: str) -> None:
    file = Path(path)
    text = file.read_text(encoding="utf-8")
    count = text.count(old)
    if count != 1:
        raise SystemExit(f"{path}: expected one match, found {count}: {old[:120]!r}")
    file.write_text(text.replace(old, new, 1), encoding="utf-8")


# Project content area: add a first-class Work tab and keep Open Folder inside Projects.
projects = "src/components/ProjectsWorkspace.tsx"
replace_once(
    projects,
    '  CheckCircle2,\n  Clock3,',
    '  Bot,\n  BriefcaseBusiness,\n  CheckCircle2,\n  Clock3,',
)
replace_once(
    projects,
    '  const [activeId, setActiveId] = useState<string | null>(null);\n  const [draftName, setDraftName] = useState("");',
    '  const [activeId, setActiveId] = useState<string | null>(null);\n  const [activePane, setActivePane] = useState<"overview" | "work">("overview");\n  const [draftName, setDraftName] = useState("");',
)
replace_once(
    projects,
    '''  const createChat = async () => {\n    if (!activeProject) return;\n    const conversation = await runAction("create-chat", async () => {\n      const created = await props.onCreateProjectChat(activeProject);\n      await api.linkProjectConversation(activeProject.id, created.id);\n      await refreshProjects(activeProject.id);\n      return created;\n    });\n    if (conversation) props.onOpenConversation(conversation.id);\n  };\n''',
    '''  const createChat = async () => {\n    if (!activeProject) return;\n    const conversation = await runAction("create-chat", async () => {\n      const created = await props.onCreateProjectChat(activeProject);\n      await api.linkProjectConversation(activeProject.id, created.id);\n      await refreshProjects(activeProject.id);\n      return created;\n    });\n    if (conversation) props.onOpenConversation(conversation.id);\n  };\n\n  const openAgentChat = async () => {\n    const existing = projectConversations[0];\n    if (existing) {\n      props.onOpenConversation(existing.id);\n      return;\n    }\n    await createChat();\n  };\n''',
)
replace_once(
    projects,
    '''          onCreated={async (project, conversation) => {\n            await refreshProjects(project.id);\n            props.onOpenConversation(conversation.id);\n          }}''',
    '''          onCreated={async (project) => {\n            await refreshProjects(project.id);\n            setActivePane("work");\n          }}''',
)
replace_once(
    projects,
    '''                  setSavedAt(null);\n                  setError(null);''',
    '''                  setSavedAt(null);\n                  setActivePane("overview");\n                  setError(null);''',
)
replace_once(
    projects,
    '''            </header>\n\n            <section className="project-card project-instructions-card">''',
    '''            </header>\n\n            <div className="project-content-tabs" role="tablist" aria-label="Project content">\n              <button\n                type="button"\n                role="tab"\n                aria-selected={activePane === "overview"}\n                className={activePane === "overview" ? "active" : ""}\n                onClick={() => setActivePane("overview")}\n              >\n                <FolderKanban size={15} /> Overview\n              </button>\n              <button\n                type="button"\n                role="tab"\n                aria-selected={activePane === "work"}\n                className={activePane === "work" ? "active" : ""}\n                onClick={() => setActivePane("work")}\n              >\n                <BriefcaseBusiness size={15} /> Work\n              </button>\n            </div>\n\n            {activePane === "overview" ? (\n              <>\n            <section className="project-card project-instructions-card">''',
)
replace_once(
    projects,
    '''            </div>\n\n            <ProjectLocalWorkspace projectId={activeProject.id} projectName={activeProject.name} />''',
    '''            </div>\n              </>\n            ) : (\n              <div className="project-work-pane">\n                <section className="project-card project-work-agent-card">\n                  <div className="project-work-agent-copy">\n                    <span className="project-work-agent-icon"><Bot size={19} /></span>\n                    <div>\n                      <span className="tools-eyebrow">Autonomous project agent</span>\n                      <h3>Work on the attached project</h3>\n                      <p>Ask OpenMindAI to inspect code, edit files, run permitted terminal commands, recover from failures, and validate the result before it reports completion.</p>\n                    </div>\n                  </div>\n                  <div className="project-work-agent-actions">\n                    <span className={projectConversations.length ? "project-work-ready" : "project-work-pending"}>\n                      {projectConversations.length ? <CheckCircle2 size={13} /> : <Sparkles size={13} />}\n                      {projectConversations.length ? `${projectConversations.length} linked chat${projectConversations.length === 1 ? "" : "s"}` : "Agent chat will be created"}\n                    </span>\n                    <button type="button" className="primary-button" disabled={busy} onClick={() => void openAgentChat()}>\n                      {busyAction === "create-chat" ? <LoaderCircle className="spin" size={15} /> : <MessageSquarePlus size={15} />}\n                      {projectConversations.length ? "Open agent chat" : "Start agent chat"}\n                    </button>\n                  </div>\n                </section>\n\n                <ProjectLocalWorkspace projectId={activeProject.id} projectName={activeProject.name} />\n              </div>\n            )}''',
)

css = Path("src/projects.css")
css_text = css.read_text(encoding="utf-8")
css_marker = "/* v3 Project Work content area */"
if css_marker not in css_text:
    css.write_text(
        css_text
        + '''\n\n/* v3 Project Work content area */\n.project-content-tabs {\n  display: inline-flex;\n  align-items: center;\n  gap: 4px;\n  width: fit-content;\n  margin: 0 0 14px;\n  padding: 4px;\n  border: 1px solid var(--border);\n  border-radius: 11px;\n  background: var(--surface-2);\n}\n\n.project-content-tabs button {\n  display: inline-flex;\n  align-items: center;\n  gap: 7px;\n  min-height: 34px;\n  padding: 0 12px;\n  border: 0;\n  border-radius: 8px;\n  background: transparent;\n  color: var(--muted);\n  font-size: 12px;\n  font-weight: 700;\n}\n\n.project-content-tabs button:hover {\n  color: var(--text);\n}\n\n.project-content-tabs button.active {\n  background: var(--surface);\n  color: var(--text);\n  box-shadow: 0 1px 3px rgb(0 0 0 / 12%);\n}\n\n.project-work-pane {\n  display: grid;\n  gap: 14px;\n}\n\n.project-work-agent-card {\n  display: flex;\n  align-items: center;\n  justify-content: space-between;\n  gap: 18px;\n  padding: 15px 16px;\n}\n\n.project-work-agent-copy {\n  display: flex;\n  align-items: flex-start;\n  gap: 12px;\n  min-width: 0;\n}\n\n.project-work-agent-icon {\n  display: grid;\n  place-items: center;\n  flex: 0 0 auto;\n  width: 38px;\n  height: 38px;\n  border: 1px solid color-mix(in srgb, var(--accent) 34%, var(--border));\n  border-radius: 11px;\n  background: color-mix(in srgb, var(--accent) 10%, var(--surface));\n  color: var(--accent);\n}\n\n.project-work-agent-card h3 {\n  margin: 2px 0 4px;\n  font-size: 15px;\n}\n\n.project-work-agent-card p {\n  max-width: 720px;\n  margin: 0;\n  color: var(--muted);\n  font-size: 12px;\n  line-height: 1.55;\n}\n\n.project-work-agent-actions {\n  display: flex;\n  align-items: flex-end;\n  flex-direction: column;\n  gap: 8px;\n  flex: 0 0 auto;\n}\n\n.project-work-agent-actions button {\n  display: inline-flex;\n  align-items: center;\n  gap: 7px;\n}\n\n.project-work-ready,\n.project-work-pending {\n  display: inline-flex;\n  align-items: center;\n  gap: 5px;\n  color: var(--muted);\n  font-size: 11px;\n  font-weight: 650;\n}\n\n.project-work-ready {\n  color: var(--success, #35a269);\n}\n\n@media (max-width: 820px) {\n  .project-work-agent-card {\n    align-items: stretch;\n    flex-direction: column;\n  }\n\n  .project-work-agent-actions {\n    align-items: flex-start;\n  }\n}\n''',
        encoding="utf-8",
    )

# Project Agent: terminal mutations invalidate validation, terminal results refresh live context,
# manifest-backed projects cannot self-skip validation, and completion includes validation evidence.
agent = "src-tauri/src/local_agent.rs"
replace_once(
    agent,
    '''    let mut validation_required = false;\n    let mut validation_deferrals = 0usize;\n    let mut status = "completed";''',
    '''    let mut validation_required = false;\n    let mut validation_deferrals = 0usize;\n    let mut last_validation_command: Option<String> = None;\n    let mut status = "completed";''',
)
replace_once(
    agent,
    '''                if validation_required\n                    && agent_context.workspace.full_pc_access\n                    && validation_skip_reason.is_none()\n                {\n                    validation_deferrals += 1;\n                    let requirement = "HOST REQUIREMENT: workspace files changed after the last successful validation. Run an appropriate test/build/lint/check command before finalizing. If no meaningful validation exists for this task, return final with a concise validationSkippedReason.";''',
    '''                let validation_skip_allowed = validation_skip_reason.is_some()\n                    && !workspace_has_validation_targets(&agent_context.workspace);\n                if validation_required\n                    && agent_context.workspace.full_pc_access\n                    && !validation_skip_allowed\n                {\n                    validation_deferrals += 1;\n                    let requirement = if workspace_has_validation_targets(&agent_context.workspace) {\n                        "HOST REQUIREMENT: workspace files changed after the last successful validation and this project contains a recognized build/test manifest. Run an appropriate test/build/lint/check command before finalizing; validationSkippedReason is not accepted for this workspace."\n                    } else {\n                        "HOST REQUIREMENT: workspace files changed after the last successful validation. Run an appropriate test/build/lint/check command before finalizing. Only when no meaningful automated validation exists may final include a concise validationSkippedReason."\n                    };''',
)
replace_once(
    agent,
    '''                let message = decision\n                    .get("message")\n                    .and_then(Value::as_str)\n                    .map(str::trim)\n                    .filter(|value| !value.is_empty())\n                    .unwrap_or("Task completed.");\n                emit_agent_chunk(\n                    app,\n                    state,\n                    conversation_id,\n                    &assistant.id,\n                    &format!("\\n{message}"),\n                )?;''',
    '''                let message = decision\n                    .get("message")\n                    .and_then(Value::as_str)\n                    .map(str::trim)\n                    .filter(|value| !value.is_empty())\n                    .unwrap_or("Task completed.");\n                let mut completion = message.to_string();\n                if let Some(command) = last_validation_command.as_deref() {\n                    completion.push_str(&format!("\\n\\nValidation: `{}` passed.", one_line(command, 240)));\n                } else if validation_required && validation_skip_allowed {\n                    if let Some(reason) = validation_skip_reason {\n                        completion.push_str(&format!(\n                            "\\n\\nValidation: skipped because {}",\n                            one_line(reason, 320)\n                        ));\n                    }\n                }\n                emit_agent_chunk(\n                    app,\n                    state,\n                    conversation_id,\n                    &assistant.id,\n                    &format!("\\n{completion}"),\n                )?;''',
)
replace_once(
    agent,
    '''                Ok(outcome) => {\n                    consecutive_failures = 0;\n                    if tool_mutates_workspace(tool) {\n                        validation_required = true;\n                        validation_deferrals = 0;\n                        if let Err(error) = refresh_agent_workspace_context(state, &mut agent_context) {\n                            push_transcript(\n                                &mut transcript,\n                                format!(\n                                    "HOST WARNING: workspace changed successfully, but the automatic workspace snapshot refresh failed: {}",\n                                    one_line(&error.to_string(), 700)\n                                ),\n                            );\n                        }\n                    }\n                    if tool == "terminal" {\n                        if let Some(command) = optional_string(&decision, "command") {\n                            if is_validation_command(&command) {\n                                validation_required = false;\n                                validation_deferrals = 0;\n                            }\n                        }\n                    }''',
    '''                Ok(outcome) => {\n                    consecutive_failures = 0;\n                    let mut workspace_changed = tool_mutates_workspace(tool);\n                    let mut successful_validation: Option<String> = None;\n\n                    if tool == "terminal" {\n                        if let Some(command) = optional_string(&decision, "command") {\n                            if is_validation_command(&command) {\n                                successful_validation = Some(command);\n                            } else if terminal_command_may_mutate_workspace(&command) {\n                                workspace_changed = true;\n                            }\n                        }\n                        if let Err(error) = refresh_agent_workspace_context(state, &mut agent_context) {\n                            push_transcript(\n                                &mut transcript,\n                                format!(\n                                    "HOST WARNING: terminal action completed, but the automatic workspace snapshot refresh failed: {}",\n                                    one_line(&error.to_string(), 700)\n                                ),\n                            );\n                        }\n                    }\n\n                    if workspace_changed {\n                        validation_required = true;\n                        validation_deferrals = 0;\n                        last_validation_command = None;\n                        if tool != "terminal" {\n                            if let Err(error) = refresh_agent_workspace_context(state, &mut agent_context) {\n                                push_transcript(\n                                    &mut transcript,\n                                    format!(\n                                        "HOST WARNING: workspace changed successfully, but the automatic workspace snapshot refresh failed: {}",\n                                        one_line(&error.to_string(), 700)\n                                    ),\n                                );\n                            }\n                        }\n                    }\n\n                    if let Some(command) = successful_validation {\n                        validation_required = false;\n                        validation_deferrals = 0;\n                        last_validation_command = Some(command);\n                    }''',
)
replace_once(
    agent,
    '''- For dependency installs or heavy builds, set timeoutSec as needed up to 600 seconds. Avoid interactive prompts, pagers, editors, sudo/password prompts, and commands that wait for user input.\\n\\\n- Follow the host shell syntax described below; do not assume Bash on Windows or PowerShell on macOS/Linux.''',
    '''- For dependency installs or heavy builds, set timeoutSec as needed up to 600 seconds. Avoid interactive prompts, pagers, editors, sudo/password prompts, and commands that wait for user input.\\n\\\n- Terminal actions that can change files (dependency installs, code generation, formatters without a check flag, migration/build scripts, Git checkout/apply operations) make earlier validation stale; validate again after them.\\n\\\n- Follow the host shell syntax described below; do not assume Bash on Windows or PowerShell on macOS/Linux.''',
)
replace_once(
    agent,
    '''fn is_validation_command(command: &str) -> bool {''',
    '''fn terminal_command_may_mutate_workspace(command: &str) -> bool {\n    let command = command.trim().to_ascii_lowercase();\n    if command.is_empty() {\n        return false;\n    }\n    let mutation_markers = [\n        ">",\n        "out-file",\n        "set-content",\n        "add-content",\n        "tee ",\n    ];\n    if mutation_markers.iter().any(|marker| command.contains(marker)) {\n        return true;\n    }\n    let read_only_prefixes = [\n        "pwd",\n        "ls",\n        "dir",\n        "get-childitem",\n        "cat ",\n        "type ",\n        "get-content",\n        "rg ",\n        "grep ",\n        "findstr ",\n        "where ",\n        "which ",\n        "git status",\n        "git diff",\n        "git log",\n        "git show",\n        "git branch --show-current",\n        "node --version",\n        "npm --version",\n        "pnpm --version",\n        "yarn --version",\n        "cargo --version",\n        "rustc --version",\n        "python --version",\n        "python3 --version",\n        "go version",\n    ];\n    !read_only_prefixes\n        .iter()\n        .any(|prefix| command == *prefix || command.starts_with(prefix))\n}\n\nfn workspace_has_validation_targets(config: &AgentWorkspaceConfig) -> bool {\n    config\n        .roots\n        .iter()\n        .any(|root| validation_target_in_directory(Path::new(&root.path), 0))\n}\n\nfn validation_target_in_directory(path: &Path, depth: usize) -> bool {\n    if depth > 2 {\n        return false;\n    }\n    let Ok(entries) = fs::read_dir(path) else {\n        return false;\n    };\n    for entry in entries.filter_map(Result::ok) {\n        let name = entry.file_name().to_string_lossy().into_owned();\n        let path = entry.path();\n        if path.is_file() && is_validation_manifest_name(&name) {\n            return true;\n        }\n        if depth < 2 && path.is_dir() && !should_skip_name(&name)\n            && validation_target_in_directory(&path, depth + 1)\n        {\n            return true;\n        }\n    }\n    false\n}\n\nfn is_validation_manifest_name(name: &str) -> bool {\n    let name = name.to_ascii_lowercase();\n    matches!(\n        name.as_str(),\n        "package.json"\n            | "cargo.toml"\n            | "pyproject.toml"\n            | "pytest.ini"\n            | "tox.ini"\n            | "go.mod"\n            | "pom.xml"\n            | "build.gradle"\n            | "build.gradle.kts"\n            | "composer.json"\n            | "gemfile"\n    ) || name.ends_with(".csproj")\n        || name.ends_with(".sln")\n}\n\nfn is_validation_command(command: &str) -> bool {''',
)
replace_once(
    agent,
    '''    fn recognizes_common_validation_commands() {\n        assert!(is_validation_command("npm run lint"));\n        assert!(is_validation_command("cargo clippy --all-targets"));\n        assert!(is_validation_command("python -m pytest -q"));\n        assert!(!is_validation_command("npm run lint && npm run build"));\n        assert!(!is_validation_command("npm test; exit 0"));\n        assert!(!is_validation_command("npm install"));\n    }\n\n    #[test]\n    fn clamps_terminal_timeout() {''',
    '''    fn recognizes_common_validation_commands() {\n        assert!(is_validation_command("npm run lint"));\n        assert!(is_validation_command("cargo clippy --all-targets"));\n        assert!(is_validation_command("python -m pytest -q"));\n        assert!(!is_validation_command("npm run lint && npm run build"));\n        assert!(!is_validation_command("npm test; exit 0"));\n        assert!(!is_validation_command("npm install"));\n    }\n\n    #[test]\n    fn classifies_terminal_workspace_mutation_conservatively() {\n        assert!(!terminal_command_may_mutate_workspace("git status --short"));\n        assert!(!terminal_command_may_mutate_workspace("rg TODO src"));\n        assert!(terminal_command_may_mutate_workspace("npm install"));\n        assert!(terminal_command_may_mutate_workspace("python scripts/codegen.py"));\n        assert!(terminal_command_may_mutate_workspace("git diff > patch.txt"));\n    }\n\n    #[test]\n    fn recognizes_validation_manifests() {\n        assert!(is_validation_manifest_name("package.json"));\n        assert!(is_validation_manifest_name("Cargo.toml"));\n        assert!(is_validation_manifest_name("OpenMindAI.csproj"));\n        assert!(!is_validation_manifest_name("README.md"));\n    }\n\n    #[test]\n    fn clamps_terminal_timeout() {''',
)

# README: document the finished project interaction without changing public release claims.
readme = "README.md"
replace_once(
    readme,
    '''Projects can group conversations, instructions, and local files. A local folder can also be opened directly as a project. Project Agent uses the attached workspace as live context and can read, create, edit, rename, or delete scoped files. When the user explicitly enables Full PC + Terminal access, the agent can run non-interactive shell commands and hardened Git status/diff inspection, recover from non-zero command failures, refresh its workspace snapshot after edits, and require appropriate validation before reporting a changed workspace as complete. Text and code files can become project context, while larger or binary files remain tracked as local project resources.''',
    '''Projects can group conversations, instructions, and local files. A local folder can also be opened directly as a project. Each project now has an Overview tab for instructions, chats, and reference files plus a Work tab for the attached local filesystem, editor, terminal permission controls, and direct handoff to the linked Project Agent chat. Project Agent uses the attached workspace as live context and can read, create, edit, rename, or delete scoped files. When the user explicitly enables Full PC + Terminal access, the agent can run non-interactive shell commands and hardened Git status/diff inspection, recover from non-zero command failures, refresh its workspace snapshot after filesystem or terminal actions, invalidate stale validation after mutating terminal commands, and require appropriate validation before reporting a changed workspace as complete. Text and code files can become project context, while larger or binary files remain tracked as local project resources.''',
)

print("v3 Project Agent and Work tab finalization staged")
